### ISSUE TITLE
OnBlockPlace NullException

### ISSUE THREAD

**Issue by sarhatabaot** [sarhatabaot/SilkSpawners#3]
## What steps will reproduce the problem?
Placing a spawner.

## Log file of the issue/error
```
[19:43:39] [Server thread/ERROR]: Could not pass event BlockPlaceEvent to SilkSpawners v6.1.2-TI-BETA
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-0309d17]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-0309d17]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:520) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-0309d17]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:505) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-0309d17]
        at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:322) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-0309d17]
        at net.minecraft.server.v1_14_R1.ItemStack.placeItem(ItemStack.java:203) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-0309d17]
        at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:476) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-0309d17]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1267) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-0309d17]
        at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-0309d17]
        at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-0309d17]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:13) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-0309d17]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot-1.14.2.jar:git-Spigot-df0eb25-0309d17]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:135) [spigot-1.14.2.jar:git-Spigot-df0eb25-0309d17]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.14.2.jar:git-Spigot-df0eb25-0309d17]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:114) [spigot-1.14.2.jar:git-Spigot-df0eb25-0309d17]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:895) [spigot-1.14.2.jar:git-Spigot-df0eb25-0309d17]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:888) [spigot-1.14.2.jar:git-Spigot-df0eb25-0309d17]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(SourceFile:99) [spigot-1.14.2.jar:git-Spigot-df0eb25-0309d17]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:871) [spigot-1.14.2.jar:git-Spigot-df0eb25-0309d17]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:805) [spigot-1.14.2.jar:git-Spigot-df0eb25-0309d17]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
Caused by: net.minecraft.server.v1_14_R1.ResourceKeyInvalidException: Non [a-z0-9/._-] character in path of location: minecraft:Pig
        at net.minecraft.server.v1_14_R1.MinecraftKey.<init>(SourceFile:38) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-0309d17]
        at net.minecraft.server.v1_14_R1.MinecraftKey.<init>(SourceFile:43) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-0309d17]
        at de.dustplanet.silkspawners.NMS.v1_14_R1.NMSHandler.setMobNameOfSpawner(NMSHandler.java:123) ~[?:?]
        at de.dustplanet.silkspawners.util.SilkUtil.setSpawnerEntityID(SilkUtil.java:454) ~[?:?]
        at de.dustplanet.silkspawners.listeners.OnBlockPlaceListener.onBlockPlace(OnBlockPlaceListener.java:77) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_191]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-0309d17]
        ... 20 more
```
## /version output?
This server is running CraftBukkit version git-Spigot-df0eb25-0309d17 (MC: 1.14.2) (Implementing API version 1.14.2-R0.1-SNAPSHOT)

## SilkSpawners version
6.1.2-TI-BETA

**Comment by NoopyyGaming** [comment]
Why with the 6.1.4 version of silkspawners when we place the cage i get 'skipping BlockEntity with ID' in console ?

**Comment by sarhatabaot** [comment]
> 
> 
> Why with the 6.1.4 version of silkspawners when we place the cage i get 'skipping BlockEntity with ID' in console ?

Could you post the exact log message?

**Comment by NoopyyGaming** [comment]
> 
> 
> > Why with the 6.1.4 version of silkspawners when we place the cage i get 'skipping BlockEntity with ID' in console ?
> 
> Could you post the exact log message?

[SKIP.txt](https://github.com/sarhatabaot/SilkSpawners/files/3553012/SKIP.txt)

**Comment by sarhatabaot** [comment]
> 
> 
> > > Why with the 6.1.4 version of silkspawners when we place the cage i get 'skipping BlockEntity with ID' in console ?
> > 
> > 
> > Could you post the exact log message?
> 
> [SKIP.txt](https://github.com/sarhatabaot/SilkSpawners/files/3553012/SKIP.txt)

Skipping BlockEntity with ID has nothing to do with SilkSpawners.
